/* this code was generated by automated tool,
   should not edit by hand */

export interface TodoList {
  ListTodo(request: _): Promise<Todos>;
  CreateTodo(request: Todo): Promise<Todo>;
}

export interface _ {}

export interface Todo {
  id?: number;
  todo?: string;
}

export interface Todos {
  todos?: Todo[];
}
